### ISSUE TITLE
Avoid database duplication

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Analytics-Module#1]
AS AN Architect
I WANT Analytics Module to consume a defined database
SO THAT we would't need to duplicate its content resulting in additional storage volume need

### Acceptance Criteria

- [ ] in case any analytics software is used, only Bürokratt database is used for data queries without any duplication of data

#### DSL

- [ ] Use Ruuter as a reverse proxy
- [ ] Use OpenSearch DSL

**Comment by turnerrainer** [comment]
This is an AC, not an issue.
