### ISSUE TITLE
Apply generic variables

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Analytics-Module#109]
AS AN Architect
I WANT all generic variables used within the project to be based on Bürokratt ADR
SO THAT they would always be named the same regardless of the service

### Acceptance Criteria

- [ ] Use https://github.com/buerokratt/Buerokratt-Architectural-Decision-Records/issues/41 as the source
- [ ] Apply changes on GUI
- [ ] Apply changes on back-end

**Comment by rasmusei** [comment]
Discussion with Rainer needed

**Comment by rasmusei** [comment]
Agreed with @turnerrainer that it is obsolete
