### ISSUE TITLE
User-specific metrics and preferences

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Analytics-Module#12]
AS AN Analytics Module User
I WANT to see the main metrics of my choice with the possibility of saving my changes
SO THAT I would always have a quick overview of my choices

### Acceptance Criteria
- [ ] person can select a metric by using checkboxes from the dropdown menu in Ülevaade (overview)
- [ ] when the metric appears in the main metrics area, the metric result is displayed there with the name of the metric
- [ ] metrics are updated after every 30 seconds, triggered by GUI
- [ ] every user can choose own metrics to be shown on the main metrics area and each time user logs in, user-specific metrics are shown
- [ ] user can change the order of main metrics by using a drag-and-drop functionality
- [ ] when calculating the metric results, #6 is taken in consideration

![Image](https://user-images.githubusercontent.com/56122140/190642394-c244c3d7-74d5-4596-ba37-bfa0a411d6f8.png)

#### GUI

- [ ] Based on https://github.com/buerokratt/Analytics-Module/issues/2
- [ ] `i18n` used
- [ ] Side menu is generated based on an endpoint providing appropriate JSON
- [ ] Dropdown values as pre-defined configurable settings, no database used
- [ ] Choose from [D3 library](https://d3js.org) and https://canvasjs.com/react-charts/ to produce graphs
- [ ] Make REST requests to fetch appropriate data to produce graphs based on User's current selection

#### DSL

- [ ] A REST endpoint `settings/metrics` to fetch user-specific metrics regarding the metrics chosen
- [x] #25

**Comment by turnerrainer** [comment]
DSL is needed to get personalised selections.
