### ISSUE TITLE
Possibility to download metric related data

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Analytics-Module#14]
AS AN Analytic module user
I WANT TO have possibility to download data that is related to each chosen metric
SO THAT I can use the data for other possible purposes I might have (copy to excel etc)

### Acceptance Criteria

- [ ] after choosing metric from the menu and the chart result is displayed, it is possible to download the related data in csv format
- [ ] button is available next to chart (or where UX/UI finds it more appropriate) for downloading the data

#### DSL

**Ruuter**

- [ ] Set appropriate headers for the browser to treat the response as a downloadable file

**Comment by turnerrainer** [comment]
@PaulaMerle please verify if it's OK business-wise to download _any_ data by anyone. A need to protect sensitive information may become an issue.
