### ISSUE TITLE
Linking chats with negative feedback (UX/UI needed)

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Analytics-Module#15]
AS AN Analytic module user
I WANT TO have direct links to the chats that have received negative feedback
SO THAT I can easily open them and analyze the reason behind the low feedback score.

### Acceptance Criteria

- [ ] when Chats with negative feedback is selected under Feedback (Tagasiside) menu, list with references/links to the chats with low score is displayed for the selected period.
- [ ] clicking to the link takes user to view the selected chat in Chats module (provided that user has right to access the chat module)
- [ ] #6 is taken into consideration

#### DSL

- [ ] Endpoint `feedback/negative` provides a JSON output of appropriate chats
- [x] #18
- [ ] #19

#### GUI

- [ ] Analytics Module lists appropriate chats with links to appropriate chat, design based on [Figma](https://www.figma.com/proto/rILEM6rghNvTsEKJ1wyQBn/B%C3%BCrokratt?node-id=280%3A5677&starting-point-node-id=1%3A2&scaling=contain)
- [ ] After clicking on a chat of interest in the Analytics Module, the detailed chat is based on [Figma design](https://www.figma.com/proto/rILEM6rghNvTsEKJ1wyQBn/B%C3%BCrokratt?node-id=280%3A5677&starting-point-node-id=1%3A2&scaling=contain)
![image](https://user-images.githubusercontent.com/90505798/211272271-3974339d-8dfd-42de-abdf-e6a1844702a9.png)

**Comment by turnerrainer** [comment]
GUI-related developments are pretty much just listing the result of chats received from a REST endpoint (provided by DSL).
