### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Analytics-Module#20]
AS A DevOps
I WANT TO set up Analytics as a whole as a Docker
SO THAT I shouldn't set all the necessary components up separately

### Acceptance Criteria

- [ ] Everything is set up by cloning the repo and running a command `docker-command up -d`
- [ ] Ruuter is installed
- [ ] Resql in installed

**Comment by 1AhmedYasser** [comment]
For Apple Silicon M1, i added `FROM --platform=linux/amd64 openjdk:17-jdk-alpine ` instead of `FROM openjdk:17-jdk-alpine` to get `docker compose up -d` working

**Comment by 1AhmedYasser** [comment]
Notes:

1) To Check if Resql container is working fine open http://localhost:8082/swagger-ui/index.html
