### ISSUE TITLE
Buerokratt feedback statistics is not shown

### ISSUE THREAD

**Issue by ValterAro** [buerokratt/Analytics-Module#291]
[BUG]
Short summary: Feedback stats are not shown for bürokratt (https://admin.test.buerokratt.ee/analytics/feedback) even though there should be datapoints present.
How to reproduce: Start a conversation with buerokratt on test.buerokratt.ee and then end the conversation and leave a evaluation score. This should then be shown in the https://admin.test.buerokratt.ee/analytics/feedback page under "feedback to buerokratt chats"
Pic:

![Image](https://github.com/buerokratt/Analytics-Module/assets/122787093/01ad3850-5b01-46db-969e-84d14d38b1f4)

**Comment by ValterAro** [comment]
The issue is also mentioned here https://github.com/orgs/buerokratt/projects/47/views/37?pane=issue&itemId=73528732 and currently still in progress.

**Comment by ValterAro** [comment]
Short summary: It should show the average of the scores (basically the average score needs to be between 0 and 10). Tested by leaving a 10, but it shows 1.
How to reproduce: go to test.buerokratt.ee and have a short conversation. Then close it and leave a feedback with a score. Then check how this score is shown in https://admin.test.buerokratt.ee/analytics/feedback under "feedback to buerokratt chats" tab at the current moment.
Also the y-axis name should be "average feedback score". 
Current pic from test environment:


![Image](https://github.com/user-attachments/assets/fd3ca796-6ab6-49a7-8802-8122c2881604)

**Comment by rasmusei** [comment]
Will do a separate task regarding Valter's last comments.

**Comment by rasmusei** [comment]
Created a sperate task for it.
