### ISSUE TITLE
Bürokrat statistics are not shown properly in the analytics module

### ISSUE THREAD

**Issue by ValterAro** [buerokratt/Analytics-Module#313]
**Short summary:** tested https://admin.prod.buerokratt.ee/analytics/overview . The statistics related to Bürokratt show zero in many cases even though they should be higher. Problematic stats in the overview - "Average chats answered by bürokrat: month / previous", "Average chats answered by bürokrat: week / previous", "Answered by bürokratt: today / Yesterday". In the feedback section there is problem with "Feedback on bureaucrat conversations" as it should show something during the last 30 days.
**How to reproduce:** have a chat with buerokratt and after ending it press that you got the answer and leave feedback. This action should be reflected in the statistics.

Pic:

![Image](https://github.com/user-attachments/assets/e890972d-a1cf-48eb-8c8a-002ff10f0477)

![Image](https://github.com/user-attachments/assets/bcf5b5dd-9092-4c05-8ae6-651f8cd1a64f)

**Comment by yb-ng** [comment]
PR: https://github.com/buerokratt/Analytics-Module/pull/316

**Comment by ValterAro** [comment]
The overview part works as intended. Will continue with the feedback part under this task https://github.com/orgs/buerokratt/projects/47/views/37?pane=issue&itemId=69337107
pic:


![Image](https://github.com/user-attachments/assets/4624c3f6-e040-4e17-a740-f60a01074a52)
