### ISSUE TITLE
[BUG] Analytics module piechart shows information in English

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Analytics-Module#338]
**Bug description:** In Analytics module, when changing chart to piechart, then information is shown in English

**Expected behavior:** Everything should be in Estonian. name = nimi and value = väärtus

**Screenshots:** ![Image](https://github.com/user-attachments/assets/9b930197-3953-4919-95c7-15ed12f58f50)

**Additional information:**

**Comment by IgorKrupenja** [comment]
Related PR: https://github.com/buerokratt/Analytics-Module/pull/349

**Comment by jaX10bt** [comment]
Works as intended
