### ISSUE TITLE
[BUG] Analytics module not showing information properly

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Analytics-Module#339]
**Bug description:** Analytics -> Chats (vestlused) -> Contact leaving (kontakti jätmised). When total (kokku) is marked, then graphs are not shown, when total is not marked, then graphs are shown. This is happening in every chart type.

**Expected behavior:** When total (kokku) is marked, then graphs are shown regarding the chart type

**Screenshots:** ![Image](https://github.com/user-attachments/assets/4fc234d6-ba75-4127-93cf-064c29de5655)
![Image](https://github.com/user-attachments/assets/10aef835-f1df-4409-9f9b-1c33b7bd8b73)

**Additional information:**

**Comment by IgorKrupenja** [comment]
Related PRs:

- https://github.com/buerokratt/DataMapper/pull/97
- https://github.com/buerokratt/Analytics-Module/pull/346

**Comment by jaX10bt** [comment]
Works as intended
