### ISSUE TITLE
Enchantment in Analytics module Negative feedback chats

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Analytics-Module#340]
**AS AN** *Analyst*
**I WANT** *to have the information there is no data in the desired view*
**SO THAT** *I would know that search from data was made even though there were no results*

### Acceptance Criteria

- [x] In Negative feedback chats in Analytics module when there are results then show the list of chats - AS IS
- [x] In Negative feedback chats in Analytics module when there are no results display a message that there are no  chats "Vestlused puuduvad". Message will be displayed in Estonian

**Comment by ffrose** [comment]
Works as intended. When there are no negative feedbacks it says "Vestlused puuduvad". It will provide the list of chats where negative feedback was added.
