### ISSUE TITLE
[BUG] Getting statistics about CSA should always get CSA's name from one source

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Analytics-Module#341]
**Bug description:** When viewing different options in Analytics regarding CSA, it displays CSA's name differently like shown in the screenshots. Although this is the same user. This is in the feedback (tagasiside) and CSA (nõustajad) section.

**Expected behavior:** There should be one source when getting CSA or other users name regarding statistics. It should be Name (Nimi) from the Users module

**Screenshots:** Pictures with the same CSA
![Image](https://github.com/user-attachments/assets/a2a7d8fd-b57f-4893-9338-31e38132257d)
![Image](https://github.com/user-attachments/assets/0d6c825c-4547-4a9a-b4a6-458239ca64ef)

**Additional information:**

**Comment by jaX10bt** [comment]
Works as intended
