### ISSUE TITLE
[BUG] Feedback to Bürokratt is not working

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Analytics-Module#343]
**Bug description:** In Analytics module and under feedback (Tagasiside) when trying to get feedback to only Bürokrat chats (Tagasiside bürokrati vestlustele) then graph is empty and does not show any data even tough there should be feedback

**Expected behavior:** Feedback to only Bürokrat chats shows data when there is feedback 

**Screenshots:**
![Image](https://github.com/user-attachments/assets/dbc7c4c5-987e-44c4-9a8e-07272f3ba520)

**Additional information:**

**Comment by IgorKrupenja** [comment]
Related PR: https://github.com/buerokratt/Analytics-Module/pull/345

**Comment by jaX10bt** [comment]
Works as intended
