### ISSUE TITLE
Analytics module  legend colors

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Analytics-Module#348]
**AS AN** *Administrator*
**I WANT** *legend colors to be more authentic*
**SO THAT** *I can easily make apart regarding different indicators*

### Acceptance Criteria

- [x] In Analytics overview module, legend colors are more authentic. Currently reds and oranges are to similar.
- [x] New corrected colors are: 1. Alustatud vestlused (hex: #89B5CB); 2. Klient lahkus vastusega (hex: #B72727); 3. Klient lahkus vastuseta (hex: #B4E282); 4. Vihakõne (hex: #F2E041); 5. Aksepteeritud vastus (hex: #13B005); 6. Muud põhjused (hex: #9D0AB4); 7. Vastus muus kanalis (hex: #320CBB)

 ![Image](https://github.com/user-attachments/assets/aaa89bcc-4e0c-459b-ac1d-b65b6e6eec31)

**Comment by ffrose** [comment]
Works as intended.
