### ISSUE TITLE
[BUG] - Metrics visualization partially missing in Overview

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Analytics-Module#58]
### Epic

[Metrics visualization under side-menu Ülevaade (overview)](https://github.com/buerokratt/Analytics-Module/issues/2)

### Tested at

http://test.buerokratt.ee:3010/analytics/overview

### Expected result

https://www.figma.com/file/Buf426ch4ToKq8dP47xJ75/B%C3%BCrokratt-Analytics-Design?node-id=0-1 -> **Ülevaade**

### Previous demo in developer's local environment

Starting from 1m 25s @  https://riigiinfosusteemiamet828.sharepoint.com/sites/Brokrattanalyticsmodule/_layouts/15/stream.aspx?id=%2Fsites%2FBrokrattanalyticsmodule%2FShared%20Documents%2FGeneral%2FRecordings%2FMeeting%20in%20%5FGeneral%5F%2D20230217%5F100115%2DMeeting%20Recording%2Emp4&OR=Teams-HL&CT=1678261874720&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIxNDE1LzIzMDIwNTAxNDIxIiwiSGFzRmVkZXJhdGVkVXNlciI6ZmFsc2V9

#### Unclear

- [ ] when selected metric involves this day statistics, the result is updated every 15 min; needs main metrics to be displayed first

##### A line chart on the bottom half of the page

- [ ] Timeline is displayed in the opposite order and time formats are too long (sufficient would be 8 PM or 20:00)

**_Expected result_**

![image](https://user-images.githubusercontent.com/90505798/223661559-07e7ff1c-538a-4cc9-85d4-5472ad15d6c1.png)

**_Actual result_**

![image](https://user-images.githubusercontent.com/90505798/223661627-31d75442-794a-4a10-b073-85262e7de5fb.png)

- [ ] Chart does not display information about the date that the data is related to

_**Expected result**_

![image](https://user-images.githubusercontent.com/90505798/223662053-82477475-b6c9-45db-9801-766844472a25.png)

_**Actual result**_

![image](https://user-images.githubusercontent.com/90505798/223662215-98efdfa9-3c95-478d-8d40-a4777f99f74e.png)

**Comment by varmoh** [comment]
Issue is: There is nothing that would generate a cookie for analytics module, thus without it, the information will not be shown.
Temporary fix to bypass this issue, is to generate a temp cookie for your browser.
![image](https://user-images.githubusercontent.com/101868197/223672885-b4ffb961-92fe-459e-a23a-23cdb1638114.png)

**Comment by 1AhmedYasser** [comment]
@PaulaMerle Please link the bug task to the PR, not the branch

**Comment by 1AhmedYasser** [comment]
> Issue is: There is nothing that would generate a cookie for analytics module, thus without it, the information will not be shown. Temporary fix to bypass this issue, is to generate a temp cookie for your browser. ![image](https://user-images.githubusercontent.com/101868197/223672885-b4ffb961-92fe-459e-a23a-23cdb1638114.png)

Will be done automatically now
