### ISSUE TITLE
Create and deploy Postgres test dataset to test Analytics Module's functionality

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Analytics-Module#60]
AS AN Acceptance Tester
I WANT TO test Analytics Module's functionality
SO THAT I could create an appropriate report

### Acceptance Criteria

- [x] Mock datasets are created and deployed at test environment
- [x] "Treening" section of http://test.buerokratt.ee:3010 is functional and responds with visual graphics based on mock data

**Comment by varmoh** [comment]
Mock database has been created and is up and running in http://test.buerokratt.ee:3010
